apiVersion: v1
kind: Pod
metadata:
  name: traffic-pod
  namespace: sdsu-hdma
spec:
  containers:
  - name: trafficpod
    image: adarsh21b/trafficsign:v1
    resources:
      limits:
        memory: 2Gi
        cpu: 2
      requests:
        memory: 1Gi
        cpu: 1
    command: ["sh", "-c", "sleep infinity"]
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - 'key': 'nautilus.io/sdsuinstruction'
            'operator': 'In'
            'values': ["true"]
  tolerations:
    - effect: NoSchedule
      key: nautilus.io/sdsu-fix
      operator: Exists
